/** LauchKix — Type definitions for app intake and launch kit generation */

/** Platform options for mobile apps */
export type Platform = "ios" | "android";

/** Tone/voice options for generated content */
export type Tone = "professional" | "playful" | "bold" | "friendly";

/** Primary goal for the app launch */
export type Goal = "downloads" | "waitlist" | "paid";

/** Language options (P1 feature) */
export type Language = "en" | "es" | "fr";

/** Input from user describing their app */
export interface AppBrief {
  name: string;
  tagline: string;
  description: string;
  platforms: Platform[];
  category: string;
  targetAudience: string;
  tone: Tone;
  goal: Goal;
  language?: Language;
}

/** Single social media post */
export interface SocialPost {
  day: number;
  platform: "X" | "LinkedIn" | "Instagram";
  hook: string;
  body: string;
  cta: string;
}

/** App Store listing content */
export interface AppStoreListing {
  title: string;
  subtitle: string;
  promotionalText: string;
  description: string;
  whatsNew: string;
}

/** Google Play Store listing content */
export interface PlayStoreListing {
  shortDescription: string;
  fullDescription: string;
}

/** ASO (App Store Optimization) keyword pack */
export interface ASOKeywords {
  primaryKeywords: string[];
  secondaryKeywords: string[];
  longTail: string[];
  tips: string[];
}

/** Launch email content */
export interface LaunchEmail {
  subjects: string[];
  body: string;
}

/** Community/Reddit launch post */
export interface CommunityPost {
  title: string;
  body: string;
}

/** Landing page copy (P1 feature) */
export interface LandingPageCopy {
  hero: string;
  subhead: string;
  features: string[];
  cta: string;
}

/** Press/media blurb (P1 feature) */
export interface PressBlurb {
  summary: string;
  founderQuote: string;
}

/** A/B test variants for store listings (P1 feature) */
export interface StoreListingVariants {
  a: {
    title: string;
    shortDescription: string;
  };
  b: {
    title: string;
    shortDescription: string;
  };
}

/** Complete launch kit generated by AI */
export interface LaunchKit {
  appStore: AppStoreListing;
  playStore: PlayStoreListing;
  aso: ASOKeywords;
  socialCalendar: SocialPost[];
  email: LaunchEmail;
  communityPost: CommunityPost;
  landingPage?: LandingPageCopy;
  pressBlurb?: PressBlurb;
  variants?: StoreListingVariants;
}

/** Metadata about the generation */
export interface GenerationMeta {
  model: string;
  durationMs: number;
  timestamp: string;
}

/** Full response from generation API */
export interface LaunchKitResponse {
  kit: LaunchKit;
  meta: GenerationMeta;
}
